---
- name: Install UFW
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ufw

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: "incoming", policy: "deny" }
    - { direction: "outgoing", policy: "allow" }

- name: Whitelist SSH port
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: "limit", port: '{{ ansible_port | default(22) }}', proto: "tcp" }

- name: Configure ufw rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    direction: "{{ item.direction }}"
    from: "{{ item.from }}"
    proto: "{{ item.proto }}"
    delete: "{{ item.delete|default('no') }}"
    comment: "{{ item.comment|default('') }}"
  with_items: "{{ ufw_rules }}"

- name: Enable UFW logging
  ufw: logging=on
  notify:
    - restart ufw

- name: Enable UFW
  ufw:
    state: enabled
  notify:
    - restart ufw
  when: ufw_enabled
